### ISSUE TITLE
scrollbar shows when typing a looooooooooooooong word

### ISSUE THREAD

**Issue by tomholub** [tomholub/cryptup-chrome#54]

**Comment by mondo989** [comment]
This could possibly be fixed with a line of css?
Can you provide anymore info? or screenshot?

**Comment by tomholub** [comment]
Not a scrollbar anymore, I guess due to some other styling changes in #45 but still gets broken:

![2016-03-11-090706_622x750_scrot](https://cloud.githubusercontent.com/assets/6306961/13690104/cc23bf8c-e768-11e5-9e9c-02f94927f942.png)

![2016-03-11-090714_622x750_scrot](https://cloud.githubusercontent.com/assets/6306961/13690108/ce1d2788-e768-11e5-9e86-7bd15f573563.png)


We're using a **contenteditable div** for the input, ideally it would break like in gmail: 

![2016-03-11-091051_555x648_scrot](https://cloud.githubusercontent.com/assets/6306961/13690170/2d598b24-e769-11e5-8d7f-5863d192b1a6.png)

**Comment by mondo989** [comment]
When a user clicks the cryptup email button, the encrypted email box appears... How is that width determined? 
Is it calculated based upon browser window size or static?

**Comment by mondo989** [comment]
I have a fix that's dependent on the the answer, if it's static then we just set a max-width

<img width="674" alt="screen shot 2016-03-10 at 11 13 27 pm" src="https://cloud.githubusercontent.com/assets/3431871/13695703/0bf9fff2-e716-11e5-898d-b152e9f5e1c9.png">

**Comment by tomholub** [comment]
https://github.com/tomholub/cryptup-chrome/blob/master/src/css/gmail.css#L20 here is the div that contains the iframe. The iframe is then set to fill 100% and inside the table as well I think.

 `width: 541px;` but minus some borders/margins/paddings etc for the text, so need to experiment a bit. It's static for now.

**Comment by mondo989** [comment]
Here's the css that fixes the bug, 

table#compose td div#input_text { border: none; overflow: none; padding-top:8px; padding-left:8px; outline: none; border: none !important; -webkit-box-shadow: none !important;
  -moz-box-shadow: none !important; box-shadow: none !important; height:100%; word-wrap: break-word; max-width: 525px;}

At the end I just added max-width 525px

**Comment by mondo989** [comment]
I can push some of the changes.... Just want to show one more thing.

**Comment by tomholub** [comment]
kk looks good!

**Comment by tomholub** [comment]
closed in 8e11f0e
